name: Testing Terraform Modules examples - Object Storage

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"

      - name: Set up dependencies
        working-directory: test/
        run: |
          go mod tidy

      - name: Testing modules
        working-directory: test/
        env:
          TF_VAR_user_ocid: ${{ secrets.USER }}
          TF_VAR_tenancy_ocid: ${{ secrets.TENANCY }}
          TF_VAR_fingerprint: ${{ secrets.FINGERPRINT }}
          TF_VAR_private_key: ${{ secrets.PRIVATE_KEY }}
          TF_VAR_compartment_ocid: ${{ secrets.COMPARTMENT_ID }}
        run: |
          go test -v object-storage_test.go
